# FROM node:alpine AS development
# WORKDIR /usr/src/app
# COPY package*.json ./
# # RUN npm install glob rimraf
# RUN npm install --only=development
# COPY . .
# # RUN npm run build

FROM node:16-alpine
WORKDIR /app
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV DB_CONN=${DB_CONN}
ENV JWT=${JWT}
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
EXPOSE $PORT
CMD ["node", "index.js"]